### ISSUE TITLE
`createDataset.py` run fails because `gbif-dl` is missing several methods.

### ISSUE THREAD

**Issue by Uberi** [plantnet/ai-taxonomist#5]
Out of the box, with `gbif-dl` version 0.1.0 (latest from PyPI):

```
$ python3 createDataset.py --data ./dataset --doi 10.15468/dl.jcnvaa
Crawling gbif
Traceback (most recent call last):
  File "createDataset.py", line 359, in <module>
    main()
  File "createDataset.py", line 198, in main
    data_generator = gbif_dl.dwca.generate_urls(
TypeError: generate_urls() got an unexpected keyword argument 'one_media_per_occurrence'
```

Instead, if you install the latest version of `gbif-dl` using `pip install git+https://github.com/plantnet/gbif-dl.git`, it gets a lot farther but still fails near the end:

```
$ python3 createDataset.py --data ./dataset --doi 10.15468/dl.jcnvaa
Crawling gbif
INFO:Download file size: 294453576 bytes
INFO:On disk at dataset/temporary/dwcas/0006226-220831081235567.zip
Retrieving images metadata...
Traceback (most recent call last):
  File "createDataset.py", line 359, in <module>
    main()
  File "createDataset.py", line 231, in main
    gbif_dl.export.to_csv(data_generator, images_file)
AttributeError: module 'gbif_dl' has no attribute 'export'
```

After some investigation, it seems like createDataset.py assumes the following workflow:

1. Create data generator.
2. Iterate over the generator and save the results to a CSV file.
3. Download the images referenced by the CSV file.

Whereas the latest version of `gbif-dl` uses the following approach instead (source: https://github.com/plantnet/gbif-dl/#downloading-images-to-disk):

1. Create data generator.
2. Download the images referenced by the data generator.

**Comment by faroit** [comment]
@Uberi a new pypi release of `gbif-dl` pending and I try to finish it of tomorrow

**Comment by faroit** [comment]
@Uberi sorry for the delay, pushing it tonight

**Comment by faroit** [comment]
@Uberi version is release, can you test again, please?

**Comment by jclombar** [comment]
@Uberi, thanks for your interest and sorry for the bad timing between @faroit and me...
I've tested on my side with gbif-dl latest version (v0.1.1) and everything seems ok.
I am closing this issue, please feel free to reopen it if needed

**Comment by Uberi** [comment]
I just had the chance to test on my end - it works great, thanks very much @faroit/@jclombar!
